// Generated by gencpp from file arlo_nn_controller/EvaluateDriver.msg
// DO NOT EDIT!


#ifndef ARLO_NN_CONTROLLER_MESSAGE_EVALUATEDRIVER_H
#define ARLO_NN_CONTROLLER_MESSAGE_EVALUATEDRIVER_H

#include <ros/service_traits.h>


#include <arlo_nn_controller/EvaluateDriverRequest.h>
#include <arlo_nn_controller/EvaluateDriverResponse.h>


namespace arlo_nn_controller
{

struct EvaluateDriver
{

typedef EvaluateDriverRequest Request;
typedef EvaluateDriverResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct EvaluateDriver
} // namespace arlo_nn_controller


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::arlo_nn_controller::EvaluateDriver > {
  static const char* value()
  {
    return "a099938bc78c367ac254aecaded19c78";
  }

  static const char* value(const ::arlo_nn_controller::EvaluateDriver&) { return value(); }
};

template<>
struct DataType< ::arlo_nn_controller::EvaluateDriver > {
  static const char* value()
  {
    return "arlo_nn_controller/EvaluateDriver";
  }

  static const char* value(const ::arlo_nn_controller::EvaluateDriver&) { return value(); }
};


// service_traits::MD5Sum< ::arlo_nn_controller::EvaluateDriverRequest> should match
// service_traits::MD5Sum< ::arlo_nn_controller::EvaluateDriver >
template<>
struct MD5Sum< ::arlo_nn_controller::EvaluateDriverRequest>
{
  static const char* value()
  {
    return MD5Sum< ::arlo_nn_controller::EvaluateDriver >::value();
  }
  static const char* value(const ::arlo_nn_controller::EvaluateDriverRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::arlo_nn_controller::EvaluateDriverRequest> should match
// service_traits::DataType< ::arlo_nn_controller::EvaluateDriver >
template<>
struct DataType< ::arlo_nn_controller::EvaluateDriverRequest>
{
  static const char* value()
  {
    return DataType< ::arlo_nn_controller::EvaluateDriver >::value();
  }
  static const char* value(const ::arlo_nn_controller::EvaluateDriverRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::arlo_nn_controller::EvaluateDriverResponse> should match
// service_traits::MD5Sum< ::arlo_nn_controller::EvaluateDriver >
template<>
struct MD5Sum< ::arlo_nn_controller::EvaluateDriverResponse>
{
  static const char* value()
  {
    return MD5Sum< ::arlo_nn_controller::EvaluateDriver >::value();
  }
  static const char* value(const ::arlo_nn_controller::EvaluateDriverResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::arlo_nn_controller::EvaluateDriverResponse> should match
// service_traits::DataType< ::arlo_nn_controller::EvaluateDriver >
template<>
struct DataType< ::arlo_nn_controller::EvaluateDriverResponse>
{
  static const char* value()
  {
    return DataType< ::arlo_nn_controller::EvaluateDriver >::value();
  }
  static const char* value(const ::arlo_nn_controller::EvaluateDriverResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ARLO_NN_CONTROLLER_MESSAGE_EVALUATEDRIVER_H
