// Generated by gencpp from file arlo_nn_controller/EvaluateDriverResponse.msg
// DO NOT EDIT!


#ifndef ARLO_NN_CONTROLLER_MESSAGE_EVALUATEDRIVERRESPONSE_H
#define ARLO_NN_CONTROLLER_MESSAGE_EVALUATEDRIVERRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace arlo_nn_controller
{
template <class ContainerAllocator>
struct EvaluateDriverResponse_
{
  typedef EvaluateDriverResponse_<ContainerAllocator> Type;

  EvaluateDriverResponse_()
    : time(0.0)
    , dist2go(0.0)
    , damage(0.0)
    , energy(0.0)  {
    }
  EvaluateDriverResponse_(const ContainerAllocator& _alloc)
    : time(0.0)
    , dist2go(0.0)
    , damage(0.0)
    , energy(0.0)  {
  (void)_alloc;
    }



   typedef double _time_type;
  _time_type time;

   typedef double _dist2go_type;
  _dist2go_type dist2go;

   typedef double _damage_type;
  _damage_type damage;

   typedef double _energy_type;
  _energy_type energy;





  typedef boost::shared_ptr< ::arlo_nn_controller::EvaluateDriverResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arlo_nn_controller::EvaluateDriverResponse_<ContainerAllocator> const> ConstPtr;

}; // struct EvaluateDriverResponse_

typedef ::arlo_nn_controller::EvaluateDriverResponse_<std::allocator<void> > EvaluateDriverResponse;

typedef boost::shared_ptr< ::arlo_nn_controller::EvaluateDriverResponse > EvaluateDriverResponsePtr;
typedef boost::shared_ptr< ::arlo_nn_controller::EvaluateDriverResponse const> EvaluateDriverResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::arlo_nn_controller::EvaluateDriverResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::arlo_nn_controller::EvaluateDriverResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::arlo_nn_controller::EvaluateDriverResponse_<ContainerAllocator1> & lhs, const ::arlo_nn_controller::EvaluateDriverResponse_<ContainerAllocator2> & rhs)
{
  return lhs.time == rhs.time &&
    lhs.dist2go == rhs.dist2go &&
    lhs.damage == rhs.damage &&
    lhs.energy == rhs.energy;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::arlo_nn_controller::EvaluateDriverResponse_<ContainerAllocator1> & lhs, const ::arlo_nn_controller::EvaluateDriverResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace arlo_nn_controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::arlo_nn_controller::EvaluateDriverResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arlo_nn_controller::EvaluateDriverResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arlo_nn_controller::EvaluateDriverResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arlo_nn_controller::EvaluateDriverResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arlo_nn_controller::EvaluateDriverResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arlo_nn_controller::EvaluateDriverResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::arlo_nn_controller::EvaluateDriverResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2d14dac515607a7113301ceb653b82dc";
  }

  static const char* value(const ::arlo_nn_controller::EvaluateDriverResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2d14dac515607a71ULL;
  static const uint64_t static_value2 = 0x13301ceb653b82dcULL;
};

template<class ContainerAllocator>
struct DataType< ::arlo_nn_controller::EvaluateDriverResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "arlo_nn_controller/EvaluateDriverResponse";
  }

  static const char* value(const ::arlo_nn_controller::EvaluateDriverResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::arlo_nn_controller::EvaluateDriverResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 time\n"
"float64 dist2go\n"
"float64 damage\n"
"float64 energy\n"
"\n"
;
  }

  static const char* value(const ::arlo_nn_controller::EvaluateDriverResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::arlo_nn_controller::EvaluateDriverResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.time);
      stream.next(m.dist2go);
      stream.next(m.damage);
      stream.next(m.energy);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EvaluateDriverResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arlo_nn_controller::EvaluateDriverResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::arlo_nn_controller::EvaluateDriverResponse_<ContainerAllocator>& v)
  {
    s << indent << "time: ";
    Printer<double>::stream(s, indent + "  ", v.time);
    s << indent << "dist2go: ";
    Printer<double>::stream(s, indent + "  ", v.dist2go);
    s << indent << "damage: ";
    Printer<double>::stream(s, indent + "  ", v.damage);
    s << indent << "energy: ";
    Printer<double>::stream(s, indent + "  ", v.energy);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARLO_NN_CONTROLLER_MESSAGE_EVALUATEDRIVERRESPONSE_H
