// Generated by gencpp from file arlo_nn_controller/EvaluateDriverRequest.msg
// DO NOT EDIT!


#ifndef ARLO_NN_CONTROLLER_MESSAGE_EVALUATEDRIVERREQUEST_H
#define ARLO_NN_CONTROLLER_MESSAGE_EVALUATEDRIVERREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace arlo_nn_controller
{
template <class ContainerAllocator>
struct EvaluateDriverRequest_
{
  typedef EvaluateDriverRequest_<ContainerAllocator> Type;

  EvaluateDriverRequest_()
    : weightsfile()
    , maxtime(0)  {
    }
  EvaluateDriverRequest_(const ContainerAllocator& _alloc)
    : weightsfile(_alloc)
    , maxtime(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _weightsfile_type;
  _weightsfile_type weightsfile;

   typedef int64_t _maxtime_type;
  _maxtime_type maxtime;





  typedef boost::shared_ptr< ::arlo_nn_controller::EvaluateDriverRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arlo_nn_controller::EvaluateDriverRequest_<ContainerAllocator> const> ConstPtr;

}; // struct EvaluateDriverRequest_

typedef ::arlo_nn_controller::EvaluateDriverRequest_<std::allocator<void> > EvaluateDriverRequest;

typedef boost::shared_ptr< ::arlo_nn_controller::EvaluateDriverRequest > EvaluateDriverRequestPtr;
typedef boost::shared_ptr< ::arlo_nn_controller::EvaluateDriverRequest const> EvaluateDriverRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::arlo_nn_controller::EvaluateDriverRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::arlo_nn_controller::EvaluateDriverRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::arlo_nn_controller::EvaluateDriverRequest_<ContainerAllocator1> & lhs, const ::arlo_nn_controller::EvaluateDriverRequest_<ContainerAllocator2> & rhs)
{
  return lhs.weightsfile == rhs.weightsfile &&
    lhs.maxtime == rhs.maxtime;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::arlo_nn_controller::EvaluateDriverRequest_<ContainerAllocator1> & lhs, const ::arlo_nn_controller::EvaluateDriverRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace arlo_nn_controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::arlo_nn_controller::EvaluateDriverRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arlo_nn_controller::EvaluateDriverRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arlo_nn_controller::EvaluateDriverRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arlo_nn_controller::EvaluateDriverRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arlo_nn_controller::EvaluateDriverRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arlo_nn_controller::EvaluateDriverRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::arlo_nn_controller::EvaluateDriverRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6e974e786534658e37e986a811914f2e";
  }

  static const char* value(const ::arlo_nn_controller::EvaluateDriverRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6e974e786534658eULL;
  static const uint64_t static_value2 = 0x37e986a811914f2eULL;
};

template<class ContainerAllocator>
struct DataType< ::arlo_nn_controller::EvaluateDriverRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "arlo_nn_controller/EvaluateDriverRequest";
  }

  static const char* value(const ::arlo_nn_controller::EvaluateDriverRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::arlo_nn_controller::EvaluateDriverRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string weightsfile\n"
"int64 maxtime\n"
;
  }

  static const char* value(const ::arlo_nn_controller::EvaluateDriverRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::arlo_nn_controller::EvaluateDriverRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.weightsfile);
      stream.next(m.maxtime);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EvaluateDriverRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arlo_nn_controller::EvaluateDriverRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::arlo_nn_controller::EvaluateDriverRequest_<ContainerAllocator>& v)
  {
    s << indent << "weightsfile: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.weightsfile);
    s << indent << "maxtime: ";
    Printer<int64_t>::stream(s, indent + "  ", v.maxtime);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARLO_NN_CONTROLLER_MESSAGE_EVALUATEDRIVERREQUEST_H
