(cl:defpackage arlo_nn_controller-srv
  (:use )
  (:export
   "ADDTWOINTS"
   "<ADDTWOINTS-REQUEST>"
   "ADDTWOINTS-REQUEST"
   "<ADDTWOINTS-RESPONSE>"
   "ADDTWOINTS-RESPONSE"
   "EVALUATEDRIVER"
   "<EVALUATEDRIVER-REQUEST>"
   "EVALUATEDRIVER-REQUEST"
   "<EVALUATEDRIVER-RESPONSE>"
   "EVALUATEDRIVER-RESPONSE"
  ))

